name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Dump Environment
        run: env
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Version
        run: exit 1 && lerna version --force
